iUse上限に達してしまう事への対応
gomo/image-proxy pull request #7
Opened 2017-06-05 06:53 UTC by shimizu-k-digi

### 概要
phpファイルを作成するのをやめてキャッシュ画像の更新時間を変更するように変える

2017-06-05 06:54 UTC, shimizu-k-digi commented
### 仕様
```
ファイルアクセス時の処理。
・キャッシュファイルがなかったら。
　┣ S3に画像を取得しに行き、キャッシュファイルを作成してレスポンスを返す。
　┗ 元ファイルがなければ、当然画像が無いレスポンスを返す。
・キャッシュファイルがあったら。
　┣ 指定時間分、経過しているかチェックする。
　┃┣ 経過していたら、S3にヘッダーを投げて、元画像の存在チェックをする。
　┃┃ ┣ 元画像が存在していたら、キャッシュファイルをそのまま帰す。
　┃┃ ┗ 元画像が存在していなかったら、キャッシュを削除して、レスポンスを返す。
　┃┗ 経過していなかったら
　┣ tachでキャッシュファイルの更新日時を今の時間で上書き。
　┗ キャッシュからレスポンスを返す。
```

2017-06-12 09:26 UTC, katsuji-anzai requested changes

2017-06-12 09:26 UTC, katsuji-anzai commented on web/ImageProxy/Http.php
> +    if(!file_exists($image->getSavePath()))
このチェックと、もう一つ、このチェック動作が終わった後に``$image->checkRemoteSize($image->size())``等として、S3上のファイルと、キャシュファイルのサイズが変わっているかを確認して、キャッシュを更新する。

処理を追加するのが簡単であれば、作業お願いします。
大変だったら、一旦やらなくてOK

:innocent:

2017-06-12 09:26 UTC, katsuji-anzai commented on web/ImageProxy/Http.php
ここのtouchをするタイミングは、
「アクセスがあったら」ではなく、
```
S3にヘッダーを送った時
```
に更新するべき日付のようなので、

下記の元々あった、touchの処理をしている時点で確認するべきらしいので、場所を変えましょう。

:innocent:

2017-06-14 06:00 UTC, shimizu-k-digi commented on web/ImageProxy/Http.php
> +    if(!file_exists($image->getSavePath()))
> S3上のファイルと、キャシュファイルのサイズが変わっているかを確認して、キャッシュを更新する。

こちらですが、キャッシュ作成の際にロスレス圧縮が行われるせいなのかキャッシュファイルと元ファイルのContent-Lengthが微妙に違う状態となります。
また「w100_○○.jpg」などサイズを変更して作成されているキャッシュファイルの場合は、元ファイルのサイズと比較するとほぼ確実にサイズが一致しないため、必ず新たなキャッシュファイルが作成されます。

上記を踏まえサイズの確認についてはこの案件では行わないことになりました。

2017-06-14 08:58 UTC, katsuji-anzai commented on web/ImageProxy/Http.php
> +    if(!file_exists($image->getSavePath()))
ファイルの更新チェックはしない方向で。
OKです。

https://github.com/SunriseDigital/nukinavi_unified/issues/418
issues作業、明日やりましょう。

2017-06-15 01:34 UTC, merged